export const SAVE_KEY = "feedTheCatSave_v1";
export const CLOUD_MOCK_KEY = "feedTheCatCloud_v1";

// Для локальной разработки можно оставить true.
// Для production в Яндекс Играх нужно выключить mock
// и выдавать награду только после реального onRewarded от SDK.
export const ALLOW_MOCK_REWARDED = true;

// GamePush SDK — единый слой под все витрины (Пикабу, VK, Telegram, OK, POKI и др.).
// ВСТАВЬ СЮДА src из тега <script> раздела "Install Code" твоего проекта в панели
// GamePush (вместе с projectId/publicToken, если они в URL). Пока строка пустая —
// GamePush не грузится и игра работает ЛОКАЛЬНО через мок (точно как раньше):
// это и страховка, и способ тестить без токена. Заполнил → загрузил на их хостинг →
// включился боевой режим. Путь относительный не нужен — это внешний https-URL.
export const GP_SDK_URL = "";

// Путь к ассетам (относительно index.html)
const A = "Assets";

export const CONFIG = {
  ingredients: {
    meat:    { name: "Мясо",   baseCost: 12, icon: `${A}/ingredients/meat.svg` },
    fish:    { name: "Рыба",   baseCost: 15, icon: `${A}/ingredients/fish.svg` },
    berries: { name: "Ягоды",  baseCost:  8, icon: `${A}/ingredients/berries.svg` },
    herbs:   { name: "Травы",  baseCost:  6, icon: `${A}/ingredients/herbs.svg` },
    milk:    { name: "Молоко", baseCost: 10, icon: `${A}/ingredients/milk.svg` },
  },

  dishes: {
    kotleta: {
      name: "Котлета",    rarity: "basic",     xp: 8,
      buff: null,
      ingredients: { meat: 1, herbs: 1 },
      icon: `${A}/dishes/kotleta.svg`,
    },
    dessert: {
      name: "Десерт",     rarity: "basic",     xp: 6,
      buff: { type: "autoclicker", mult: 1.15, duration: 45 },
      ingredients: { milk: 1, berries: 2 },
      icon: `${A}/dishes/dessert.svg`,
    },
    ukha: {
      name: "Уха",        rarity: "medium",    xp: 20,
      buff: { type: "click", mult: 1.2, duration: 60 },
      ingredients: { fish: 1, herbs: 1, berries: 1 },
      icon: `${A}/dishes/ukha.svg`,
    },
    feast: {
      name: "Пиршество",  rarity: "medium",    xp: 50,
      buff: { type: "all", mult: 1.5, duration: 30 },
      ingredients: { fish: 2, meat: 2, milk: 1 },
      icon: `${A}/dishes/feast.svg`,
    },
    rainbow: {
      name: "Радужный пир", rarity: "legendary", xp: 120,
      buff: { type: "all", mult: 2.0, duration: 60 },
      ingredients: { fish: 2, meat: 2, milk: 1, berries: 2, herbs: 2 },
      icon: `${A}/dishes/rainbow.svg`,
    },
  },

  rarityMultiplier: { basic: 1.0, medium: 1.5, legendary: 2.5 },

  skins: {
    1: { name: "Бельчик", idle: `${A}/skins/skin_01/skin_01_0_512x512.webp`, click: `${A}/skins/skin_01/skin_01_1_512x512.webp`, color: "#ff6b35", passive: "fluffy",    desc: "XP кормления (до +120%)" },
    2: { name: "Казимир", idle: `${A}/skins/skin_02/skin_02_0_512x512.webp`, click: `${A}/skins/skin_02/skin_02_1_512x512.webp`, color: "#95a5a6", passive: "swordsman", desc: "Шанс и сила крита" },
    3: { name: "Огонёк", idle: `${A}/skins/skin_03/skin_03_0_512x512.webp`, click: `${A}/skins/skin_03/skin_03_1_512x512.webp`, color: "#e67e22", passive: "fire",      desc: "Доход ручного клика (до +100%)" },
    4: { name: "Теньчик",   idle: `${A}/skins/skin_04/skin_04_0_512x512.webp`, click: `${A}/skins/skin_04/skin_04_1_512x512.webp`, color: "#8e44ad", passive: "shadow",    desc: "Доход автокликера (до +100%)" },
    5: { name: "Соня",   idle: `${A}/skins/skin_05/skin_05_0_512x512.webp`, click: `${A}/skins/skin_05/skin_05_1_512x512.webp`, color: "#3498db", passive: "sleepy",    desc: "Скидка на ингредиенты (до -25%)" },
    6: { name: "Батончик", idle: `${A}/skins/skin_06/skin_06_0_512x512.webp`, click: `${A}/skins/skin_06/skin_06_1_512x512.webp`, color: "#d4ac0d", passive: "baton",   desc: "Двойное блюдо + скидка на блюда" },
    7: { name: "Куся",  idle: `${A}/skins/skin_07/skin_07_0_512x512.webp`, click: `${A}/skins/skin_07/skin_07_1_512x512.webp`, color: "#27ae60", passive: "dragon",    desc: "Урон по боссу + быстрее респаун" },
    8: { name: "Снежок", idle: `${A}/skins/skin_08/skin_08_0_512x512.webp`, click: `${A}/skins/skin_08/skin_08_1_512x512.webp`, color: "#bdc3c7", passive: "angel",     desc: "Смягчает гарант + баффы дольше" },
    9: { name: "Искра",  idle: `${A}/skins/skin_09/skin_09_0_512x512.webp`, click: `${A}/skins/skin_09/skin_09_1_512x512.webp`, color: "#f1c40f", passive: "kazya",     desc: "Опыт игрока за клик (до +80%)" },
    10:{ name: "Абрикосик", idle: `${A}/skins/skin_10/skin_10_0_512x512.webp`, click: `${A}/skins/skin_10/skin_10_1_512x512.webp`, color: "#e74c3c", passive: "imper",     desc: "Звёзды хаоса при престиже (до +100%)" },
  },

  upgrades: {
    bowls:          { name: "Миски",          desc: "+10% XP кормления за тир",       max: 10, cost: (t) => 3 * (t + 1) },
    training:       { name: "Тренировка",     desc: "+5% дохода клика за тир",        max: 10, cost: (t) => 3 * (t + 1) },
    storage:        { name: "Хранилище",      desc: "+1 к дневному лимиту блюд",      max: 10, cost: (t) => 2 * (t + 1) },
    boss_damage:    { name: "Урон по боссу",  desc: "+15% урона по боссу за тир",     max: 10, cost: (t) => 4 * (t + 1) },
    gacha_discount: { name: "Скидка гачи",    desc: "-1 pity за тир, максимум 3",     max:  3, cost: (t) => 6 * (t + 1) },
  },

  uiIcons: {
    shop:     `${A}/ui_icons/icon_shop.svg`,
    cooking:  `${A}/ui_icons/icon_cooking.svg`,
    feed:     `${A}/ui_icons/icon_feed.svg`,
    skins:    `${A}/ui_icons/icon_skins.svg`,
    boss:     `${A}/ui_icons/icon_boss.svg`,
    prestige: `${A}/ui_icons/icon_prestige.svg`,
    settings: `${A}/ui_icons/icon_settings.svg`,
    gacha:    `${A}/ui_icons/icon_gacha.svg`,
    coin:     `${A}/svg_anim/fx_coin_spin.svg`,
    coinHud:  `${A}/svg_anim/fx_coin_static.svg`,
    star:     `${A}/ui_icons/icon_star.svg`,
    buff:     `${A}/ui_icons/icon_buff.svg`,
    close:    `${A}/ui_icons/icon_close.svg`,
    clock:    `${A}/ui_icons/icon_clock.svg`,
    flagRu:   `${A}/ui_icons/flag_ru.svg`,
    globe:    `${A}/ui_icons/globe.svg`,
    ribbon:   `${A}/ui_icons/icon_ribbon.svg`,
    gift:     `${A}/ui_icons/icon_gift.svg`,
    party:    `${A}/ui_icons/icon_party.svg`,
    paw:      `${A}/ui_icons/icon_paw.svg`,
    cat:      `${A}/ui_icons/icon_cat.svg`,
    ticket:   `${A}/ui_icons/icon_ticket.svg`,
    sparkle:  `${A}/ui_icons/icon_sparkle.svg`,
    trophy:   `${A}/ui_icons/icon_trophy.svg`,
    broken:   `${A}/ui_icons/icon_broken.svg`,
    lock:     `${A}/ui_icons/icon_lock.svg`,
    gem:      `${A}/ui_icons/icon_gem.svg`,
    cloud:    `${A}/ui_icons/icon_cloud.svg`,
    tv:       `${A}/ui_icons/icon_tv.svg`,
    heart:    `${A}/ui_icons/icon_heart.svg`,
  },

  backgrounds: {
    main:     `${A}/backgrounds/background_main.webp`,
    shop:     `${A}/backgrounds/background_shop.webp`,
    gacha:    `${A}/backgrounds/background_gacha.webp`,
    boss:     `${A}/backgrounds/background_boss.webp`,
    prestige: `${A}/backgrounds/background_prestige.webp`,
  },

  boss: {
    sprite: `${A}/boss/boss_01.webp`,
    icon:   `${A}/boss/boss_icon_128.webp`,
  },

  gacha: {
    cardBack:  `${A}/gacha/gacha_card_back.webp`,
    glow:      `${A}/gacha/gacha_glow.webp`,
    newBanner: `${A}/gacha/gacha_new_skin_banner.webp`,
  },
};

export const I18N = {
  ru: {
    ui: {
      gameTitle: "Накорми котика после битвы",
      loading: "Загрузка {percent}%",
      shop: "Магазин",
      cook: "Готовка",
      feed: "Кормить",
      skins: "Скины",
      boss: "Босс",
      prestige: "Престиж",
      gacha: "Гача",
      settings: "Настройки",
      ingredients: "Ингредиенты",
      readyDishes: "Готовые блюда",
      price: "Цена",
      stock: "Запас",
      inventory: "Инвентарь",
      dailyLimit: "Лимит за день",
      shopNoXp: "Магазин не даёт опыт",
      cookBtn: "Приготовить",
      feedBtn: "Покормить",
      noDishes: "Нет блюд. Открой готовку и приготовь еду.",
      feedingXp: "Опыт кормления",
      buff: "Бафф",
      amount: "Количество",
      noBuff: "нет",
      click: "клик",
      autoclicker: "авто",
      all: "всё",
      autoclickerLabel: "Авто",
      on: "ВКЛ",
      off: "ВЫКЛ",
      selected: "Выбран",
      select: "Выбрать",
      onlyGacha: "Только гача",
      locked: "Закрыт",
      gachaGuarantee: "Гарант",
      autoOpenCards: "Автооткрытие карт",
      watchAd10: "Смотреть рекламу ×10",
      oneViewTenRewards: "Один просмотр = 10 наград.",
      guaranteeHint: "Когда шкала гаранта заполнится — выпадет скин {{heart}}",
      resultsX10: "Результаты ×10",
      spinAgain: "Крутить ещё",
      backToGacha: "Назад к гаче",
      bossTier: "Босс, тир {tier}",
      bossFight: "Бой с боссом",
      fight: "Бой!",
      startFight: "Начать бой",
      attack: "Атака",
      bossDuration: "Бой длится 60 секунд.",
      bossWin: "Победа!",
      bossLose: "Поражение",
      bossReward: "Награда: {{coin}} {coins}",
      bossConsolation: "Утешительные монеты: {{coin}} {coins}",
      toBoss: "К боссу",
      bossReady: "Босс готов к бою!",
      bossAppearsIn: "До появления босса: {time}",

      bossWinReward: "Победа: {{coin}} {coins}, {dishes}, усиление всего ×1.2.",
      bossLosePenalty: "Поражение: 25% монет и перезарядка 28 часов.",
      chaosStars: "Звёзды хаоса: {stars}{{starglow}}",
      prestigeAvailable100: "Престиж доступен на 100 уровне.",
      currentLevel: "Текущий уровень: {level}.",
      canGetStars: "База: {base}{{star}} · с бонусами: {total}{{star}}.",
      prestigeStarsHint: "До 100 уровня звёзды не начисляются. Прокачивай скины и открывай новых — при сбросе получишь звёзды хаоса за прогресс скинов.",
      prestigeResets: "Сбрасываются: монеты, уровень, ингредиенты, блюда, лимиты, баффы.",
      prestigeKeeps: "Сохраняются: скины, уровни скинов, улучшения, звёзды, статистика.",
      doPrestige: "Выполнить престиж",
      upgradesForStars: "Улучшения за звёзды",
      buyForStars:  "Купить за {cost}{{star}} ",
      max: "МАКС",
      tier: "Тир {tier}/{max}",
      sound: "Звук",
      music: "Музыка",
      sfxVolume: "Громкость эффектов",
      musicVolume: "Громкость музыки",
      vibration: "Вибрация",
      damageNumbers: "Числа урона",
      screenShake: "Тряска экрана",
      reduceMotion: "Уменьшить движение",
      effectsQuality: "Качество эффектов",
      language: "Язык",
      qualityLow: "Низкое",
      qualityMedium: "Среднее",
      qualityHigh: "Высокое",
      progressAutoSave: "Прогресс сохраняется автоматически {{cloud}}",
      version: "Версия",
      platform: "Платформа",
      platformMock: "локальная",
      platformYandex: "Яндекс Игры",
      levelShort: "Ур.",
      perSecond: "/с",
      secondsShort: "с",
      xpShort: "Опыт",
      levelUp: "Уровень повышен!",
      skinLevelUp: "Скин повышен!",
      cookDone: "Готово!",
      prestigeFx: "Престиж!",
      tutorial0: "Погладь котика 3 раза.",
      tutorial1: "Открой магазин.",
      tutorial2: "В магазине купи мясо.",
      tutorial3: "Теперь купи травы.",
      tutorial4: "Закрой магазин — нажми на крестик {{close}}. ",
      tutorial5: "Открой готовку.",
      tutorial6: "Приготовь котлету из мяса и трав.",
      tutorial7: "Закрой готовку — нажми на крестик {{close}}. ",
      tutorial8: "Покорми котика котлетой.",
      tutorial9: "Открой босса — посмотри, кто там живёт.",
      tutorial10:  "Закрой босса — нажми на крестик {{close}}. Бой подождёт окончания обучения. ",
      tutorial11: "Открой гачу.",
      tutorial12: "Нажми на кнопку крутки — первая крутка бесплатная.",
      tutorial13: "Закрой гачу — нажми на крестик {{close}}. ",
      tutorialSkip: "Пропустить",
      tutorialPrefix: "Обучение: {text}",
      bossWaitTutorial: "Сначала закончи обучение — босс подождёт! {{paw}}",
      notEnoughCoins: "Недостаточно монет.",
      ingredientLimit: "Дневной лимит ингредиентов исчерпан.",
      dishLimit: "Дневной лимит готовых блюд исчерпан.",
      noDish: "Нет этого блюда.",
      notEnoughIngredients: "Не хватает ингредиентов.",
      doubleDish: "Батончик помог: двойное блюдо!",
      autoclickerUnlocked: "Автокликер открыт и включён!",
      playerLevelToast: "Уровень игрока: {level}!",
      skinLevelToast: "{name}: уровень {level}!",
      prestigeToast: "Престиж! Получено звёзд: {stars}.",
      upgradeMax: "Улучшение максимального уровня.",
      notEnoughStars: "Недостаточно звёзд хаоса.",
      gachaNoPulls: "Дневные попытки гачи закончились.",
      adNotCompleted: "Награда не выдана: реклама не завершена.",
      mockReward: "Тестовая реклама: награда через 1 сек...",
      bossAvailableIn: "Босс будет доступен через {time}.",
      tutorialAdvance: "Обучение: шаг вперёд!",
      tutorialComplete: "Обучение завершено!",
      tutorialReward: "Обучение завершено! Бонус: +50{{coin}} и 1 котлета {{meat}}",
      firstPullFree: "{{gift}} Первая крутка бесплатно",
      tutorialRewardTitle: "Поздравляем! {{party}}",
      tutorialRewardBody: "Ты прошёл обучение! Держи награду за старание: +50{{coin}} и 1 котлета {{meat}}",
      tutorialRewardOk: "Забрать награду",
      skinShop: "Магазин скинов",
      skinShopSoon: "Магазин скинов откроется совсем скоро {{ribbon}}",
      soon: "скоро",
      buy: "Купить",
      recipe: "Состав",
      feeding: "Кормление",
      hoursShort: "ч",
      minutesShort: "м",
      loadError: "Ошибка загрузки. Открой консоль.",
      prestigeConfirmTitle: "Сбросить прогресс?",
      prestigeConfirmBody:  "Престиж обнулит уровень, монеты и запасы — но ты получишь {stars}{{star}} звёзд хаоса. Скины, улучшения и звёзды останутся с тобой. ",
      prestigeConfirmYes:  "Сбросить и забрать {stars}{{star}} ",
      prestigeConfirmNo: "Передумал",
    },
    ingredients: {
      meat: "Мясо",
      fish: "Рыба",
      berries: "Ягоды",
      herbs: "Травы",
      milk: "Молоко",
    },
    dishes: {
      kotleta: "Котлета",
      dessert: "Десерт",
      ukha: "Уха",
      feast: "Пиршество",
      rainbow: "Радужный пир",
    },
    skins: {
      1: { name: "Бельчик", desc: "XP кормления (до +120%)" },
      2: { name: "Казимир", desc: "Шанс и сила крита" },
      3: { name: "Огонёк", desc: "Доход ручного клика (до +100%)" },
      4: { name: "Теньчик", desc: "Доход автокликера (до +100%)" },
      5: { name: "Соня", desc: "Скидка на ингредиенты (до -25%)" },
      6: { name: "Батончик", desc: "Двойное блюдо + скидка на блюда" },
      7: { name: "Куся", desc: "Урон по боссу + быстрее респаун" },
      8: { name: "Снежок", desc: "Смягчает гарант + баффы дольше" },
      9: { name: "Искра", desc: "Опыт игрока за клик (до +80%)" },
      10: { name: "Абрикосик", desc: "Звёзды хаоса при престиже (до +100%)" },
    },
    upgrades: {
      bowls: { name: "Миски", desc: "+10% опыта кормления за тир" },
      training: { name: "Тренировка", desc: "+5% дохода клика за тир" },
      storage: { name: "Хранилище", desc: "+1 к дневному лимиту блюд" },
      boss_damage: { name: "Урон по боссу", desc: "+15% урона по боссу за тир" },
      gacha_discount: { name: "Скидка гачи", desc: "-1 к гаранту за тир, максимум 3" },
    },
  },
  en: {
    ui: {
      gameTitle: "Feed the Cat After Battle",
      loading: "Loading {percent}%",
      shop: "Shop",
      cook: "Cooking",
      feed: "Feed",
      skins: "Skins",
      boss: "Boss",
      prestige: "Prestige",
      gacha: "Gacha",
      settings: "Settings",
      ingredients: "Ingredients",
      readyDishes: "Ready Meals",
      price: "Price",
      stock: "Stock",
      inventory: "Inventory",
      dailyLimit: "Daily limit",
      shopNoXp: "Shop does not give experience",
      cookBtn: "Cook",
      feedBtn: "Feed",
      noDishes: "No meals. Open cooking and prepare food.",
      feedingXp: "Feeding experience",
      buff: "Buff",
      amount: "Amount",
      noBuff: "none",
      click: "click",
      autoclicker: "auto",
      all: "all",
      autoclickerLabel: "Auto",
      on: "ON",
      off: "OFF",
      selected: "Selected",
      select: "Select",
      onlyGacha: "Gacha only",
      locked: "Locked",
      gachaGuarantee: "Guarantee",
      autoOpenCards: "Auto-open cards",
      watchAd10: "Watch ad ×10",
      oneViewTenRewards: "One view = 10 rewards.",
      guaranteeHint: "A skin drops when the guarantee bar fills {{heart}}",
      resultsX10: "Results ×10",
      spinAgain: "Spin again",
      backToGacha: "Back to gacha",
      bossTier: "Boss, tier {tier}",
      bossFight: "Boss Fight",
      fight: "Fight!",
      startFight: "Start Fight",
      attack: "Attack",
      bossDuration: "The fight lasts 60 seconds.",
      bossWin: "Victory!",
      bossLose: "Defeat",
      bossReward: "Reward: {{coin}} {coins}",
      bossConsolation: "Consolation coins: {{coin}} {coins}",
      toBoss: "To Boss",
      bossReady: "Boss is ready for battle!",
      bossAppearsIn: "Boss appears in: {time}",

      bossWinReward: "Victory: {{coin}} {coins}, {dishes}, all ×1.2 buff.",
      bossLosePenalty: "Defeat: 25% coins and 28 hour cooldown.",
      chaosStars: "Chaos stars: {stars}{{starglow}}",
      prestigeAvailable100: "Prestige is available at level 100.",
      currentLevel: "Current level: {level}.",
      canGetStars: "Base: {base}{{star}} · with bonuses: {total}{{star}}.",
      prestigeStarsHint: "No stars are granted before level 100. Level up your skins and unlock new ones — on reset you'll earn chaos stars for skin progress.",
      prestigeResets: "Resets: coins, level, ingredients, meals, limits, buffs.",
      prestigeKeeps: "Keeps: skins, skin levels, upgrades, stars, statistics.",
      doPrestige: "Perform Prestige",
      upgradesForStars: "Upgrades for stars",
      buyForStars:  "Buy for {cost}{{star}} ",
      max: "MAX",
      tier: "Tier {tier}/{max}",
      sound: "Sound",
      music: "Music",
      sfxVolume: "Effects volume",
      musicVolume: "Music volume",
      vibration: "Vibration",
      damageNumbers: "Damage numbers",
      screenShake: "Screen shake",
      reduceMotion: "Reduce motion",
      effectsQuality: "Effects quality",
      language: "Language",
      qualityLow: "Low",
      qualityMedium: "Medium",
      qualityHigh: "High",
      progressAutoSave: "Progress is saved automatically {{cloud}}",
      version: "Version",
      platform: "Platform",
      platformMock: "local",
      platformYandex: "Yandex Games",
      levelShort: "Lv.",
      perSecond: "/s",
      secondsShort: "s",
      xpShort: "XP",
      levelUp: "Level up!",
      skinLevelUp: "Skin level up!",
      cookDone: "Done!",
      prestigeFx: "Prestige!",
      tutorial0: "Pet the cat 3 times.",
      tutorial1: "Open the shop.",
      tutorial2: "In the shop, buy meat.",
      tutorial3: "Now buy herbs.",
      tutorial4: "Close the shop — tap the {{close}} button. ",
      tutorial5: "Open cooking.",
      tutorial6: "Cook a cutlet from meat and herbs.",
      tutorial7: "Close cooking — tap the {{close}} button. ",
      tutorial8: "Feed the cat the cutlet.",
      tutorial9: "Open the boss — see who lives there.",
      tutorial10: "Close the boss — tap the {{close}} button. The fight will wait until the tutorial ends. ",
      tutorial11: "Open the gacha.",
      tutorial12: "Tap the spin button — your first spin is free.",
      tutorial13: "Close the gacha — tap the {{close}} button. ",
      tutorialSkip: "Skip",
      tutorialPrefix: "Tutorial: {text}",
      bossWaitTutorial: "Finish the tutorial first — the boss can wait! {{paw}}",
      notEnoughCoins: "Not enough coins.",
      ingredientLimit: "Daily ingredient limit reached.",
      dishLimit: "Daily ready meal limit reached.",
      noDish: "You do not have this meal.",
      notEnoughIngredients: "Not enough ingredients.",
      doubleDish: "Baton helped: double meal!",
      autoclickerUnlocked: "Autoclicker unlocked and enabled!",
      playerLevelToast: "Player level: {level}!",
      skinLevelToast: "{name}: level {level}!",
      prestigeToast: "Prestige! Stars received: {stars}.",
      upgradeMax: "Upgrade is at maximum level.",
      notEnoughStars: "Not enough chaos stars.",
      gachaNoPulls: "Daily gacha attempts are over.",
      adNotCompleted: "Reward not granted: ad not completed.",
      mockReward: "Test ad: reward in 1 second...",
      bossAvailableIn: "Boss will be available in {time}.",
      tutorialAdvance: "Tutorial: step forward!",
      tutorialComplete: "Tutorial complete!",
      tutorialReward: "Tutorial complete! Bonus: +50{{coin}} and 1 cutlet {{meat}}",
      firstPullFree: "{{gift}} First spin free",
      tutorialRewardTitle: "Congratulations! {{party}}",
      tutorialRewardBody: "You finished the tutorial! Here is a reward for your effort: +50{{coin}} and 1 cutlet {{meat}}",
      tutorialRewardOk: "Claim reward",
      skinShop: "Skin Shop",
      skinShopSoon: "Skin shop is coming soon {{ribbon}}",
      soon: "soon",
      buy: "Buy",
      recipe: "Ingredients",
      feeding: "Feeding",
      hoursShort: "h",
      minutesShort: "m",
      loadError: "Loading failed. Open console.",
      prestigeConfirmTitle: "Reset progress?",
      prestigeConfirmBody: "Prestige resets your level, coins and supplies — but you gain {stars}{{star}} chaos stars. Skins, upgrades and stars stay with you. ",
      prestigeConfirmYes: "Reset & take {stars}{{star}} ",
      prestigeConfirmNo: "Never mind",
    },
    ingredients: {
      meat: "Meat",
      fish: "Fish",
      berries: "Berries",
      herbs: "Herbs",
      milk: "Milk",
    },
    dishes: {
      kotleta: "Cutlet",
      dessert: "Dessert",
      ukha: "Fish Soup",
      feast: "Feast",
      rainbow: "Rainbow Pie",
    },
    skins: {
      1: { name: "Belchik", desc: "Feeding XP bonus" },
      2: { name: "Kazimir", desc: "Critical hit bonus" },
      3: { name: "Ogonyok", desc: "Manual click bonus" },
      4: { name: "Tenchik", desc: "Autoclicker bonus" },
      5: { name: "Sonya", desc: "Ingredient discount (up to -25%)" },
      6: { name: "Batonchik", desc: "Chance for double meal when cooking" },
      7: { name: "Kusya", desc: "Boss damage bonus" },
      8: { name: "Snezhok", desc: "Softens gacha guarantee" },
      9: { name: "Iskra", desc: "Player XP per click (up to +80%)" },
      10: { name: "Abrikosik", desc: "Chaos stars bonus" },
    },
    upgrades: {
      bowls: { name: "Bowls", desc: "+10% feeding XP per tier" },
      training: { name: "Training", desc: "+5% click income per tier" },
      storage: { name: "Storage", desc: "+1 daily meal limit" },
      boss_damage: { name: "Boss Damage", desc: "+15% boss damage per tier" },
      gacha_discount: { name: "Gacha Discount", desc: "-1 guarantee per tier, max 3" },
    },
  },
};
